spring.application.name=MENU
server.port=8092

spring.datasource.url=jdbc:mysql://localhost:3306/menu2_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Eureka Client (Service Discovery)
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

# Enable Config Client
spring.cloud.config.enabled=true
spring.cloud.config.uri=${SPRING_CLOUD_CONFIG_URI:http://localhost:8585}

# Feign logging
logging.level.tn.esprit.menu.client=DEBUG
